### ISSUE TITLE
Allow Parent reference while indexing 

### ISSUE THREAD

**Issue by ganarajpr** [voldern/elasticsearch-bulk-index-stream#10]
Currently the bulk indexing stream does not support parent references while indexing. ElasticSearch supports `has_parent` and `has_child` relationships between various types in an index. This cannot be currently done using the existing implementation.

Please include support for the same. 

Reference : 

https://www.elastic.co/guide/en/elasticsearch/guide/current/parent-child.html

https://www.elastic.co/guide/en/elasticsearch/guide/current/parent-child-mapping.html

**Comment by voldern** [comment]
This was resolved in https://github.com/voldern/elasticsearch-bulk-index-stream/pull/9. I just forgot to close the issue.
